name: Run ripper.sh

on: 
  workflow_dispatch: # Allows manual trigger in GitHub Actions

jobs:
  run-ripper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set permissions for ripper.sh
        run: chmod +x ripper.sh

      - name: Run ripper.sh
        run: ./ripper.sh
